id: I1009D708
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T21:02:07.764836'
last_modified: '2022-06-18T21:02:07.764848'
parser: null
source_metadata:
  title: The Great Religious History by Sa skya paṇḍi ta (1182–1251)
  author: sa skya paNDi ta kun dga rgyal mtshan/
  description: 'Digital version 2.0 {Wylie}; WYLIE COPY of master xml (completed:
    2020-01-18); no thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre; This text was published by the Paltsek
    Research Institute. (src)
  - Text input:dpal brtsegs bod yig dpe rnying zhib 'jug khang / (Lhasa) (pts)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/4640
  bases:
    33d7:
      title: The Great Religious History by Sa skya paṇḍi ta (1182–1251)
      order: 1
      base_file: 33d7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
